import "./globals.css";
import Layout from "./components/layout/Layout";
import localFont from "next/font/local";
import ThemeRegistry from "./components/modules/muiRegistry/ThemeRegistry";
const vazirmatn = localFont({
  src: [{ path: "./fonts/Vazirmatn-Medium.ttf" }],
  variable: "--font-vazirmatn",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirmatn.variable} antialiased`}>
        <ThemeRegistry>
          <Layout>{children}</Layout>
        </ThemeRegistry>
      </body>
    </html>
  );
}
